bitcoin/messages.py
To replicate the bug run the following commands in python console:
>>> import bitcoin
>>> from bitcoin.messages import msg_addr
>>> bitcoin.SelectParams('testnet')
>>> msg_addr().to_bytes()[0]
'\xf9'
Notice that the magic byte is set for main, not testnet.
After my change: 
>>> import bitcoin
>>> from bitcoin.messages import msg_addr
>>> bitcoin.SelectParams('testnet')
>>> msg_addr().to_bytes()[0]
'\x0b'
Notice that the magic byte(s) are correct for testnet.
Happy new years. =)
=> Fixing bug where to_bytes clobbers testnet params.

bitcoin/rpc.py
Adds specific handling of the dumpprivkey call, ensuring the address is converted to a string on input, and the result is wrapped as a BitcoinSecret.
=> Add dumpprivkey call support

bitcoin/messages.py, bitcoin/net.py, bitcoin/tests/test_messages.py
also use b2lx instead of hexlify for python3 support.
=> Add msg_notfound, msg_reject and CTransaction.id()

bitcoin/rpc.py
Two minor changes to bitcoin.rpc.RawProxy:
Do not assume that bitcoin.conf file specifies rpcuser.
Use port 443 as default for https RPC connections.
=> bitcoin.rpc.RawProxy, 443 as default port for HTTPS and more robust parsing of bitcoin.conf

examples/bip-0070-payment-protocol.py, examples/make-bootstrap-rpc.py, examples/spend-p2pkh-txout.py, examples/spend-p2sh-txout.py, examples/timestamp-op-ret.py
wasn't running strait off on my mac.
=> [examples] remove hardcoded python executable

bitcoin/net.py, bitcoin/tests/test_net.py, examples/send-addrs-msg.py
Added IPv6 support to addr messages + sanity tests. 
I tested this code against a bitcoin node using a v4 ip address patched to accept v6 addr messages to confirm capability with bitcoind.
I also validated the hex in wireshark.
I added example code used to check IPv6 comparability.
=> adding IPv6 supprt to addr messages with example code

bitcoin/core/serialize.py
Adds missing number of bytes to error message when too many bytes are requested in
a single read.
=> Correct error message in ser_read

bitcoin/core/key.py
OpenSSL 1.0.1k rejects non-canonical DER signatures, this patch decodes and then
re-encodes the signature before verification to ensure a consistent result.
=> OpenSSL 1.0.1k compatibility

bitcoin/core/key.py, bitcoin/core/script.py, bitcoin/tests/test_script.py, bitcoin/tests/test_wallet.py
This ensures all signatures have the lowest possible S value. Where S values are above half the order of the curve, the order of the curve is subtracted from the S value in order to reduce it.
Additional tests for signing added as part of this process.
Low-S value checks have been added to script.py as they are part of script code in Bitcoin Core, but may make more sense in key.py, let me know what you think?
=> Generate low-S DER signatures

bitcoin/core/__init__.py, bitcoin/tests/test_core.py
Enables support for blockchains whose MAX_MONEY does not match Bitcoin via subclassing of CoreChainParams().
=> Move MAX_MONEY into a core chain parameter

bitcoin/__init__.py
Previously MainParams inherited from CoreChainParams, which meant the core main network parameters
were not set.
This is primarily useful if you're, for example, working with more than just the Bitcoin networks and want to use the genesis block hash as a unique blockchain identifier.
=> Switch MainParams to inherit from CoreMainParams

bitcoin/core/serialize.py, bitcoin/tests/test_serialize.py
Add support for encoding uint256 values to compact form.
Add unit tests for compact for decode/encode
Add code to handle very small compact values (these are unlikely in real data, however should be handled anyway)
=> Add support for encoding to compact form

bitcoin/core/key.py
In [Fedora](http://fedoraproject.org/) openssl not support secp256k1 by default..  (may be also in other fedora based os)
[Bug 1021898 - Enable curve secp256k1 ](https://bugzilla.redhat.com/show_bug.cgi?id=1021898) for details
=> raise Exception when secp256k1 not supported

bitcoin/rpc.py
Because the importaddress RPC call requires having something in the label parameter in order to check the rescan parameter, I changed the default value of label to an empty string. The code now sends an RPC call with all of the parameters every time, such that all cases are handled properly.
Alternatively, the default value can remain None, but this would require if-else spaghetti.
=> Update importaddress rpc call to handle no label, rescan=False

bitcoin/rpc.py, examples/ssl-rpc-connection.py
This pull request allows for verifying the JSON-RPC connection's SSL self-signed certificate
=> Fix ssl json rpc connection

bitcoin/core/key.py, bitcoin/signature.py, bitcoin/signmessage.py, bitcoin/tests/data/signmessage.json, bitcoin/tests/test_signmessage.py, bitcoin/wallet.py, examples/sign-message.py
**Work in Progress**
I ported the code for pubkey recovery from bitcoin core using ctypes, the same way as the other code is written.
The `VerifyMessage` (and `BitcoinMessage` class) are still in the `test_signverify_message.py` because I have no idea where you would want these to go? please let me know where you want me to put them
I'm not entirely sure about the `CPubKey.recover_compact`, as a python dev I'd say it should be a `@classmethod` (like it is now) but to match the bitcoin core code (which is what you've been doing) should it be different?
tested against `py2.7` and `py3.4`, to test it against `libeay` I have to run it on windows I guess, or is it 100% certain that everything 'just works'?
PS. is there any particular reason for not having travis-ci setup to run the tests on …
=> add verifying signed message, using pubkey recovery

bitcoin/rpc.py, release-notes.md
As discussed in #73, plus a small step toward PEP8.
=> Split Proxy from RawProxy to enforce forward-compatible code

bitcoin/rpc.py
Switching to `simplejson` seems to improve CPU and memory use, particularly for the expensive `getrawmempool(True)`.
I also tried `ujson` but it doesn't support the `parse_float` parameter.
=> rpc: support (but don't require) simplejson

.gitignore, README, runtests.sh, tox.ini
Add tox support for automating tests across multiple Python versions and for gathering coverage statistics.
This is what I used for reproducing #30 and for testing #77 and #79. I thought I'd share in case it was useful.
=> READY FOR REVIEW - Add tox support for coverage and multiple python versions

bitcoin/rpc.py
For daemons without a wallet the 'paytxfee' field does not exist.
=> Fix getinfo() RPC where disablewallet=1

bitcoin/core/scripteval.py
Pretty straightforward fix, self was omitted from the constructor.
Also removed an unused import.
=> Fixed attribute creation for EvalScriptError

bitcoin/bloom.py, bitcoin/tests/test_bloom.py
Previous code was invalid and not tested (_ser_read is not declared in the scope and the name isn't even right), plus self was used in a classmethod before the 'self' variable declaration. Also removed another unused import. 
It's now fixed and tested.
```
py27: commands succeeded
py33: commands succeeded
py34: commands succeeded
py35: commands succeeded
pypy: commands succeeded
SKIPPED:  pypy3: InterpreterNotFound: pypy3
stats: commands succeeded
congratulations :)
```
=> Fixed a bug in bloom filter deserialization

bitcoin/core/serialize.py, bitcoin/net.py, bitcoin/tests/test_bloom.py, bitcoin/tests/test_key.py, bitcoin/tests/test_net.py, bitcoin/tests/test_serialize.py
* Improved coverage for bitcoin/net.py to 96%
* Fixed three bugs
* CUnsignedAlert.deserialize referenced invalid functions
* intVectorSerializer would always return None when deserializing data
* Serializer.stream_deserialized can be called with a bytes or str argument but expects a _BytesIO
* Removed unused imports and variables
=> Bugfixing and more test coverage for bitcoin/net.py

MANIFEST.in, setup.py
This adds LICENSE to the dist tarball, and the trove license classification to the uploaded PyPI metadata.
=> Add license info for PyPI

bitcoin/rpc.py, release-notes.md
Removed in Bitcoin Core v0.12.0 to reduce dependencies on OpenSSL.
Is anyone using this? SSH tunnels are a good alternative, as is using stunnel (as suggested in the Bitcoin Core release notes for v0.12.0).
=> Remove RPC over SSL support

MANIFEST.in
Should resolve an issue that occurs when specifying `python-bitcoinlib==0.6.0` in `install_requires` in `setup.py`:
```
Searching for python-bitcoinlib==0.6.0
Reading https://pypi.python.org/simple/python-bitcoinlib/
Best match: python-bitcoinlib 0.6.0
Downloading https://pypi.python.org/packages/d9/b4/547a82648cab2db3b7622ecb3b19f1c40c03fe810d33bef2695d45b01376/python-bitcoinlib-0.6.0.tar.gz#md5=f4ea5084cc8af552effe1bc0288d258d
Processing python-bitcoinlib-0.6.0.tar.gz
Writing /tmp/easy_install-ovmbcw19/python-bitcoinlib-0.6.0/setup.cfg
Running python-bitcoinlib-0.6.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ovmbcw19/python-bitcoinlib-0.6.0/egg-dist-tmp-7k7se_cv
error: [Errno 2] No such file or directory: '/tmp/easy_install-ovmbcw19/python-bitcoinlib-0.6.0/README.md'
```
To …
=> Add missing README.md to MANIFEST.in

bitcoin/rpc.py
This pull request fills out newly added option **subtractfeefromamount** introduced in Bitcoin 0.11. It is used in the *sendmany* and *sendtoaddress* calls and will subtract the transaction fee from the amount rather than adding it on top of it. Since the target bitcoin version is 0.11 this should be safe for installs. 
Without adding these options it will retain existing functionality. Also had to add the comment parameters for *sendtoaddress* which were missing.
Ran the runtests.sh for this pull request, not sure what this all means, but the changes are simple and I've tested on my app.
```
Name                                 Stmts   Miss  Cover
--------------------------------------------------------
bitcoin/__init__.py                     31      8    74%
bitcoin/base58.py …
```
=> Adds sendtoaddress options comments, subtractfeefromamount

bitcoin/core/script.py, bitcoin/tests/test_script.py
python-bitcoinlib currently deserializes the null byte `0x00` or `OP_0` as an empty binary string, `b''`.  I even see that in the tests this behavior may be intentional.  I suggest that it be changed to interpret `0x00` as a small integer, to make it consistent with the other small integers.  People looking for empty data pushes can always use raw_iter.
The reason this matters is that Segregated Witness uses a byte, interpreted as a small integer, as its "witness version".  This byte for V1 witness transactions currently being created is 0x00.  
I want to make this change to save future users looking at segwit transactions some confusion when their transaction is deserialized with a `x('')` instead of `0` for the witness version.
=> Interpret 0x00 as OP_0 instead of b''

bitcoin/rpc.py
New function to unlock the wallet from the code.
=> Added walet unlocking function

examples/sign-message.py
This adds command line parsing of message and key to the sign-message.py example:
```
$ ./sign-message.py -h                                                  (sign-message-cli|✔)
usage: sign-message.py [-h] [-v] -k KEY -m MSG
Sign a message with a private key.
optional arguments:
-h, --help         show this help message and exit
-v, --verbose      verbose output
-k KEY, --key KEY  private key in base58 encoding
-m MSG, --msg MSG  message to sign
Security warning: arguments may be visible to other users on the same host.
$ ./sign-message.py -m 'hello world' -k 'L4vB5fomsK8L95wQ7GFzvErYGht49JsCPJyJMHpB4xGM6xgi2jvG'
H5fuPQBm4Vmb5q19cbxgkH769SgSkotl9I+qGgKF3ytyE8L/rZgq3c1aYPY4wIAVNlzJ++T4+6WZlKO5diIukyY=
$ ./sign-message.py -v -m 'hello world' -k …
```
=> Add CLI argument parsing to sign-message.py example.

bitcoin/rpc.py
Use the .cookie file from the bitcoin config folder if there is no rpcpassword specified in the bitcoin.conf file. Also removes username/password from service url. Credentials are already in the authorization field. Sending them via both methods should not be necessary
https://en.wikipedia.org/wiki/Basic_access_authentication
=> Add support for cookie file authentication

bitcoin/messages.py
This resolves an issue I uncovered while updating `pynode` to work with `python-bitcoinlib` 0.7.0. The following usage was previously allowable, because `CBlock` was mutable:
```py
db_block = self.chaindb.getblock(blkhash)
block = copy.copy(db_block)
block.vtx = []
msg.headers.append(block)
```
I [updated it](https://github.com/jgarzik/pynode/pull/19/files#diff-97b3827045a89ffba8170a14179aeb74L373) to the following, which resulted in the type error that this PR fixes:
```py
block = self.chaindb.getblock(blkhash)
msg.headers.append(block.get_header())
```
=> Serialize msg_header using CBlockHeader instead of CBlock

bitcoin/rpc.py
So far it is not possible to close a connection. you need to hope that GC does it or access `__connection` over the `__dict__` variable.
This PR let the proxy expose a proper `close()` function.
=> Make it possible to explicitly close RPC connection

MANIFEST.in
Currently the .json files from the data subdir are not included within the pypi tarball, thus making the tests fail when invoking the test suite from the pypi fetched unzipped tarball.
=> Add the data subdir from the tests within the pypi tarball.

bitcoin/core/script.py
Fix struct.unpack receiving an integer instead of a byte. 
Before I was receiving this error
```
File "/python-bitcoinlib/venv/lib/python3.6/site-packages/python_bitcoinlib-0.9.0-py3.6.egg/bitcoin/core/script.py", line 684, in is_witness_scriptpubkey
return 3 <= len(self) <= 42 and CScriptOp(struct.unpack('<b',self[0])[0]).is_small_int()
TypeError: a bytes-like object is required, not 'int'
```
Solved by getting the byte with self[0:1]. A bytearray of length 1 that is accepted by unpack.
Check https://stackoverflow.com/q/29299136/
=> Fix struct.unpack receiving an integer instead of a byte

bitcoin/messages.py
According to bip-0037
Version messages above 70001 require a Relay Flag
By default is true, but you can change to false with setter.
https://github.com/bitcoin/bips/blob/master/bip-0037.mediawiki
=> implement bip-0037 in version message

bitcoin/rpc.py
If datadir is specified in bitcoin.conf, bitcoind will write the .cookie file there.
=> look for .cookie file in datadir if specified

setup.py
Set `long_description_content_type='text/markdown'`.
See also https://github.com/opentimestamps/python-opentimestamps/pull/30
=> Enable README markdown rendering on PyPI

bitcoin/rpc.py
I found this while I was looking around the code. "true/false" argument is no longer documented in bitcoin core's rpc, This comment might be helpful for those who look this in detail.
We could change the argument to be 0 instead of false, however, it would break if someone is using bitcoin-core before v0.15.0.
=> add comment on an argument of getblock rpc

bitcoin/tests/fakebitcoinproxy.py, bitcoin/tests/test_fakebitcoinproxy.py
FakeBitcoinProxy provides an interface similar to the bitcoin.rpc.Proxy API. Downstream applications interested in unit testing can use FakeBitcoinProxy as an alternative to elaborate Proxy mocks. This interface returns similar values as Proxy and is intended to have similar behavior.
Unit tests are provided and they are passing.
We've been using FakeBitcoinProxy since 2015 to test many different bitcoin applications, which have also been tested against bitcoin nodes running on regtest, testnet and mainnet. Specifically, we pass in FakeBitcoinProxy instead of a bitcoin connection and we get back the same behavior in these different environments using the same interface.
Ideally, this contribution would also include tests to show parity between Proxy and FakeBitcoinProxy, even against …
=> FakeBitcoinProxy: a mock RPC implementation.

bitcoin/core/key.py
* BN_bin2bn happy to take null ptr as arg and do allocation.
* EC_POINT_mul hears you the first time, don't need to call twice.
* EC_KEY_set_private_key makes a copy of the key; without freeing it we have a memory leak.
=> misc fixes key.py

bitcoin/rpc.py
This small pul requests fixes a compatibility with python27 by by defining FileNotFoundError.
=> Fix python 27 incompatibility by defining FileNotFoundError

bitcoin/rpc.py
add clarifying comment, see #203
=> add comment to __getattr__ in RawProxy to clarify the intent of check

bitcoin/rpc.py
Fixing #209 
Added `generatetoaddress(self,numblocks,addr)` to rpc.py, which should replace `generate(self,numblocks)`. The latter will be dropped in bitcoin-core v0.19.
Keeping `generate(self,numblocks)` for now (for backward compatibility)
=>  Added generatetoaddress(self,numblocks,addr) to rpc.py

bitcoin/core/script.py
Model CScript.is_witness_scriptpubkey after bitcoind's
CScript::IsWitnessProgram -- it not only checks for script size
and first opcode, but also checks that data push size equals
script size + 2 (entire script consists of version byte
and data push). In absense of this check, is_witness_scriptpubkey
wrongfully detects 1-of-1 p2sh redeem script as a witness program.
=> CScript.is_witness_scriptpubkey : size must match second byte + 2

bitcoin/rpc.py
This allows to handle disconnects and reconnections
outside the library, by supplying your own
connection object instead of httplib.HTTPConnection
=> BaseProxy: allow to specify custom connection

bitcoin/rpc.py
Sometimes there is a need to issue RPC commands to the services
that just pretend to be bitcoind, and are emulating some of its commands.
These services might not follow the same protocol for error reporting
as bitcoind does. An example of such service would be feesim
(https://github.com/bitcoinfees/feesim, Model-based Bitcoin fee estimation)
With these changes, we can handle non-standard error responses
gracefully.
=> handle non-standard RPC responses

bitcoin/core/key.py, bitcoin/tests/test_wallet.py
This is done in a straightforward way, as we added specific functions to check for presence of libsecp256k1 and to enable using it for signing. We or someone else might devise a universal way to plug in different signing libraries, later. This can be used today by someone who need RFC6979 signing, and also may be useful when implementing pluggable signing library scheme.
Two new functions are added to core/key.py:
is_libsec256k1_available() -- to check that libsec256k1 is present
in the system
use_libsecp256k1_for_signing(do_use) - if do_use is True, sign() function will use libsec256k1 (it will check _libsecp256k1_enable_signing global flag)
if do_use is False, _libsecp256k1_enable_signing flag is set to False, and openssl will be used within sign() function.
=> add ability to use libsecp256k1 for signing (supports RFC6979)

bitcoin/core/script.py
After discussing in [this issue](https://github.com/petertodd/python-bitcoinlib/issues/176), I think it is better to keep the methods signatures, but change the comments and fix a potential bug.
=> fix checking on p2sh-p2wsh

bitcoin/rpc.py
signrawtransaction is deprecated from bitcoincore 0.17.0
and removed from bitcoincore 0.18.0
=> added rpc call signrawtransactionwithwallet

bitcoin/wallet.py
The error message should say 'not a P2WPKH scriptPubKey'
=> Fix error message for invalid P2WSH scriptPubKey.

bitcoin/wallet.py
This was incorrect. I guess the author copy-pasted the code from somewhere or was thinking of `return NotImplemented` (which wouldn't even make sense here).
=> Fix incorrect use of NotImplementedError

examples/spend-p2wsh-txout.py
Here is an example for generating a P2WSH address and spending from it. The example is set up for use on testnet, and requires funding the newly generated address before it can be spent from.
=> [examples] Added example for spending from P2WSH output.

bitcoin/core/serialize.py
There is a small typo in bitcoin/core/serialize.py.
Should read `probably` rather than `probabably`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, probabably -> probably

examples/spend-p2wsh-txout.py
redeemScript should refer to the value that needs to be revealed in order to spend the utxo. In the previous version of the example, redeemScript was the scriptPubKey which isn't right.
=> Fix misuse of the term redeemScript in p2wsh example

bitcoin/rpc.py
The current implementation of getrawtransaction doesn't allow to provide the block hash. This PR is meant to fill this gap.
=> Update getrawtransaction to work with block hash argument

README.md, bitcoin/__init__.py, bitcoin/core/__init__.py, bitcoin/rpc.py, examples/make-bootstrap-rpc.py
Add its constant into `SelectParams`.
=> Make signet usable

bitcoin/core/contrib/ripemd160.py, bitcoin/core/serialize.py, bitcoin/tests/test_ripemd160.py
Newer versions of OpenSSL have removed support for `ripemd160` by default which results in an `ValueError: unsupported hash type ripemd160` exception being raised any time the `Hash160` function is used within `python-bitcoinlib`.
See https://github.com/bitcoin/bitcoin/issues/23710 for further details of the issue.
This PR adds a fallback to a pure-python implementation of ripemd160. The code is taken from https://github.com/bitcoin/bitcoin/pull/23716, and the implementation here is based on https://github.com/diybitcoinhardware/embit/commit/2e293b000d20562327151c72a4aed672d0a944bc
=> Add fallback to pure-python ripemd160

bitcoin/core/key.py
Fixes #239.
I agree with @dgpv, any padding should be performed by the user and we shouldn't be doing any unexpected transformations on the user's secret key material. So we just raise an exception if anything other than exactly 32 bytes are passed.
=> Check that secrets are exactly 32 bytes

examples/spend-p2wpkh.py
I think this makes the explanation more correct. There is no such thing as an "implicit template" really.
=> Remove wrong text in P2WPKH example explanation

bitcoin/messages.py
The serializer expects bytes, but strSubVer is a string. So it needs to be encoded first.
=> Pass strSubVer.encode() to serializer

bitcoin/rpc.py
The data directory for the cookie file used for authentication should be `~/.bitcoin/testnet3` when connecting to bitcoin core testnet through RPC.
=> Fix file location of .cookie when on testnet

bitcoin/rpc.py
Allows using HTTPS URLs when configuring a Bitcoin proxy:
```python
import bitcoin.rpc
btc_proxy = bitcoin.rpc.Proxy(
service_url="https://<some-rpc-id>.btc.quiknode.pro/<api-secret>"
)
```
=> Add HTTPS to supported RPC Proxy protocols

bitcoin/core/key.py
In modern version of openssl (iirc from 1.1) the
library `libeay32` is removed in favour of libcrypto.
See for more info https://github.com/openssl/openssl/issues/10332
This commit adds the possibility to include libcrypto too
Fixing the following error on a nix shell
```
/home/vincent/.cache/pypoetry/virtualenvs/lampo-lnprototest-IQvPSNpc-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py:325: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown. Plugin: helpconfig, Hook: pytest_cmdline_parse
ConftestImportFailure: OSError: libeay32: cannot open shared object file: No such file or directory (from /home/vincent/gittea/work/lampo.rs/tests/lnprototest/tests/conftest.py) For more information see …
```
=> core: support openssl 3

bitcoin/core/serialize.py
The closing parenthesis in the docstring should be removed.
=> Update serialize.py (Docstring Typo:)

bitcoin/core/key.py
Looks like the fix in https://github.com/petertodd/python-bitcoinlib/pull/301 was not working.
I got the following error while trying to run `from bitcoin.rpc import Proxy` on my machine
```
File ~\OneDrive\Documents\GitHub\python-bitcoinlib\bitcoin\rpc.py:38
36 from bitcoin.core import COIN, x, lx, b2lx, CBlock, CBlockHeader, CTransaction, COutPoint, CTxOut
37 from bitcoin.core.script import CScript
---> 38 from bitcoin.wallet import CBitcoinAddress, CBitcoinSecret
40 DEFAULT_USER_AGENT = "AuthServiceProxy/0.1"
42 DEFAULT_HTTP_TIMEOUT = 30
File ~\OneDrive\Documents\GitHub\python-bitcoinlib\bitcoin\wallet.py:23
21 import bitcoin.bech32
22 import bitcoin.core
---> 23 import bitcoin.core.key
24 import bitcoin.core.script as script
27 class CBitcoinAddress(object):
File …
```
=> core: Fix a bug with loading libcrypto
